// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: pb_comment.proto

package com.line.ticket.mini.model;

public final class PbComment {
  private PbComment() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface CommentOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.line.ticket.mini.model.Comment)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string commentContent = 1;</code>
     * @return The commentContent.
     */
    java.lang.String getCommentContent();
    /**
     * <code>string commentContent = 1;</code>
     * @return The bytes for commentContent.
     */
    com.google.protobuf.ByteString
        getCommentContentBytes();

    /**
     * <code>int32 replyCount = 2;</code>
     * @return The replyCount.
     */
    int getReplyCount();

    /**
     * <code>bool status = 3;</code>
     * @return The status.
     */
    boolean getStatus();
  }
  /**
   * Protobuf type {@code com.line.ticket.mini.model.Comment}
   */
  public static final class Comment extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.line.ticket.mini.model.Comment)
      CommentOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Comment.newBuilder() to construct.
    private Comment(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Comment() {
      commentContent_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Comment();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Comment(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              commentContent_ = s;
              break;
            }
            case 16: {

              replyCount_ = input.readInt32();
              break;
            }
            case 24: {

              status_ = input.readBool();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.line.ticket.mini.model.PbComment.internal_static_com_line_ticket_mini_model_Comment_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.line.ticket.mini.model.PbComment.internal_static_com_line_ticket_mini_model_Comment_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.line.ticket.mini.model.PbComment.Comment.class, com.line.ticket.mini.model.PbComment.Comment.Builder.class);
    }

    public static final int COMMENTCONTENT_FIELD_NUMBER = 1;
    private volatile java.lang.Object commentContent_;
    /**
     * <code>string commentContent = 1;</code>
     * @return The commentContent.
     */
    @java.lang.Override
    public java.lang.String getCommentContent() {
      java.lang.Object ref = commentContent_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        commentContent_ = s;
        return s;
      }
    }
    /**
     * <code>string commentContent = 1;</code>
     * @return The bytes for commentContent.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getCommentContentBytes() {
      java.lang.Object ref = commentContent_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        commentContent_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int REPLYCOUNT_FIELD_NUMBER = 2;
    private int replyCount_;
    /**
     * <code>int32 replyCount = 2;</code>
     * @return The replyCount.
     */
    @java.lang.Override
    public int getReplyCount() {
      return replyCount_;
    }

    public static final int STATUS_FIELD_NUMBER = 3;
    private boolean status_;
    /**
     * <code>bool status = 3;</code>
     * @return The status.
     */
    @java.lang.Override
    public boolean getStatus() {
      return status_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getCommentContentBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, commentContent_);
      }
      if (replyCount_ != 0) {
        output.writeInt32(2, replyCount_);
      }
      if (status_ != false) {
        output.writeBool(3, status_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getCommentContentBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, commentContent_);
      }
      if (replyCount_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, replyCount_);
      }
      if (status_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(3, status_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.line.ticket.mini.model.PbComment.Comment)) {
        return super.equals(obj);
      }
      com.line.ticket.mini.model.PbComment.Comment other = (com.line.ticket.mini.model.PbComment.Comment) obj;

      if (!getCommentContent()
          .equals(other.getCommentContent())) return false;
      if (getReplyCount()
          != other.getReplyCount()) return false;
      if (getStatus()
          != other.getStatus()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + COMMENTCONTENT_FIELD_NUMBER;
      hash = (53 * hash) + getCommentContent().hashCode();
      hash = (37 * hash) + REPLYCOUNT_FIELD_NUMBER;
      hash = (53 * hash) + getReplyCount();
      hash = (37 * hash) + STATUS_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getStatus());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.line.ticket.mini.model.PbComment.Comment parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.line.ticket.mini.model.PbComment.Comment parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.line.ticket.mini.model.PbComment.Comment parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.line.ticket.mini.model.PbComment.Comment parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.line.ticket.mini.model.PbComment.Comment parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.line.ticket.mini.model.PbComment.Comment parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.line.ticket.mini.model.PbComment.Comment parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.line.ticket.mini.model.PbComment.Comment parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.line.ticket.mini.model.PbComment.Comment parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.line.ticket.mini.model.PbComment.Comment parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.line.ticket.mini.model.PbComment.Comment parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.line.ticket.mini.model.PbComment.Comment parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.line.ticket.mini.model.PbComment.Comment prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.line.ticket.mini.model.Comment}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.line.ticket.mini.model.Comment)
        com.line.ticket.mini.model.PbComment.CommentOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.line.ticket.mini.model.PbComment.internal_static_com_line_ticket_mini_model_Comment_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.line.ticket.mini.model.PbComment.internal_static_com_line_ticket_mini_model_Comment_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.line.ticket.mini.model.PbComment.Comment.class, com.line.ticket.mini.model.PbComment.Comment.Builder.class);
      }

      // Construct using com.line.ticket.mini.model.PbComment.Comment.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        commentContent_ = "";

        replyCount_ = 0;

        status_ = false;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.line.ticket.mini.model.PbComment.internal_static_com_line_ticket_mini_model_Comment_descriptor;
      }

      @java.lang.Override
      public com.line.ticket.mini.model.PbComment.Comment getDefaultInstanceForType() {
        return com.line.ticket.mini.model.PbComment.Comment.getDefaultInstance();
      }

      @java.lang.Override
      public com.line.ticket.mini.model.PbComment.Comment build() {
        com.line.ticket.mini.model.PbComment.Comment result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.line.ticket.mini.model.PbComment.Comment buildPartial() {
        com.line.ticket.mini.model.PbComment.Comment result = new com.line.ticket.mini.model.PbComment.Comment(this);
        result.commentContent_ = commentContent_;
        result.replyCount_ = replyCount_;
        result.status_ = status_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.line.ticket.mini.model.PbComment.Comment) {
          return mergeFrom((com.line.ticket.mini.model.PbComment.Comment)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.line.ticket.mini.model.PbComment.Comment other) {
        if (other == com.line.ticket.mini.model.PbComment.Comment.getDefaultInstance()) return this;
        if (!other.getCommentContent().isEmpty()) {
          commentContent_ = other.commentContent_;
          onChanged();
        }
        if (other.getReplyCount() != 0) {
          setReplyCount(other.getReplyCount());
        }
        if (other.getStatus() != false) {
          setStatus(other.getStatus());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.line.ticket.mini.model.PbComment.Comment parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.line.ticket.mini.model.PbComment.Comment) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object commentContent_ = "";
      /**
       * <code>string commentContent = 1;</code>
       * @return The commentContent.
       */
      public java.lang.String getCommentContent() {
        java.lang.Object ref = commentContent_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          commentContent_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string commentContent = 1;</code>
       * @return The bytes for commentContent.
       */
      public com.google.protobuf.ByteString
          getCommentContentBytes() {
        java.lang.Object ref = commentContent_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          commentContent_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string commentContent = 1;</code>
       * @param value The commentContent to set.
       * @return This builder for chaining.
       */
      public Builder setCommentContent(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        commentContent_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string commentContent = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearCommentContent() {
        
        commentContent_ = getDefaultInstance().getCommentContent();
        onChanged();
        return this;
      }
      /**
       * <code>string commentContent = 1;</code>
       * @param value The bytes for commentContent to set.
       * @return This builder for chaining.
       */
      public Builder setCommentContentBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        commentContent_ = value;
        onChanged();
        return this;
      }

      private int replyCount_ ;
      /**
       * <code>int32 replyCount = 2;</code>
       * @return The replyCount.
       */
      @java.lang.Override
      public int getReplyCount() {
        return replyCount_;
      }
      /**
       * <code>int32 replyCount = 2;</code>
       * @param value The replyCount to set.
       * @return This builder for chaining.
       */
      public Builder setReplyCount(int value) {
        
        replyCount_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 replyCount = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearReplyCount() {
        
        replyCount_ = 0;
        onChanged();
        return this;
      }

      private boolean status_ ;
      /**
       * <code>bool status = 3;</code>
       * @return The status.
       */
      @java.lang.Override
      public boolean getStatus() {
        return status_;
      }
      /**
       * <code>bool status = 3;</code>
       * @param value The status to set.
       * @return This builder for chaining.
       */
      public Builder setStatus(boolean value) {
        
        status_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bool status = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearStatus() {
        
        status_ = false;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.line.ticket.mini.model.Comment)
    }

    // @@protoc_insertion_point(class_scope:com.line.ticket.mini.model.Comment)
    private static final com.line.ticket.mini.model.PbComment.Comment DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.line.ticket.mini.model.PbComment.Comment();
    }

    public static com.line.ticket.mini.model.PbComment.Comment getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Comment>
        PARSER = new com.google.protobuf.AbstractParser<Comment>() {
      @java.lang.Override
      public Comment parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Comment(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Comment> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Comment> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.line.ticket.mini.model.PbComment.Comment getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_line_ticket_mini_model_Comment_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_line_ticket_mini_model_Comment_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020pb_comment.proto\022\032com.line.ticket.mini" +
      ".model\"E\n\007Comment\022\026\n\016commentContent\030\001 \001(" +
      "\t\022\022\n\nreplyCount\030\002 \001(\005\022\016\n\006status\030\003 \001(\010b\006p" +
      "roto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_line_ticket_mini_model_Comment_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_line_ticket_mini_model_Comment_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_line_ticket_mini_model_Comment_descriptor,
        new java.lang.String[] { "CommentContent", "ReplyCount", "Status", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
